import type { Metadata } from "next";
import { Inter, Noto_Serif, Source_Code_Pro } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

// const notoSerif = Noto_Serif({
//   variable: "--font-noto-serif",
//   subsets: ["latin"],
//   // Regular: 400, Medium: 500, SemiBold: 600, Bold: 700
//   weight: ["400", "500", "600", "700"],
// });

// const sourceCodePro = Source_Code_Pro({
//   variable: "--font-source-code-pro",
//   subsets: ["latin"],
//   // Regular: 400, Medium: 500, SemiBold: 600, Bold: 700
//   weight: ["400", "500", "600", "700"],
// });

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  // Regular: 400, Medium: 500, SemiBold: 600, Bold: 700
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.variable} antialiased bg-white dark:bg-Neutral-950`}>
        <ThemeProvider attribute="class" defaultTheme="light">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
